Contribution-file add
ProyectLink/super-list-frontend pull request #36
Opened 2024-10-02 17:57 UTC by Mukesh-ghildiyal

#27 contrbution file added

2024-10-02 18:06 UTC, bryanlundberg requested changes
Should work fine that description, just discard the package-lock.json changes. 👌

2024-10-02 18:06 UTC, bryanlundberg commented on package-lock.json
Avoid to commit this change.

2024-10-03 04:31 UTC, Mukesh-ghildiyal commented on package-lock.json
might ne now its ok i guess?

2024-10-03 13:36 UTC, bryanlundberg commented on package-lock.json
There's must be only 1 file changed on the PR.+
![image](https://github.com/user-attachments/assets/3e5c12a4-622d-44b8-adfc-96499aceea23)

2024-10-03 16:01 UTC, Mukesh-ghildiyal commented on package-lock.json
might be its just showing as a formatting changes i didn't do any changes in it

2024-10-04 19:56 UTC, bryanlundberg commented
Fixed: #42 

Sorry, @Mukesh-ghildiyal this task was delaying my time to review other PR.

2024-10-04 19:56 UTC, closed without merging