feat: created settings page issues #18 #19
ProyectLink/super-list-frontend pull request #37
Opened 2024-10-02 19:19 UTC by namansharma3007

I have successfully completed the following updates:

### Built the settings page.
- Resolved issues #18 and #19.
- Ensured all changes adhere to the project’s file structure, with modifications located in the ```/components/settings``` directory.
- Additionally, I have attached a video as proof of functionality.

https://github.com/user-attachments/assets/20b32f5a-c54b-4ed2-b2a6-bf832faf3039

2024-10-03 13:50 UTC, bryanlundberg commented
> @bryanlundberg Please check this PR

I'm on that 👌

2024-10-03 13:54 UTC, namansharma3007 commented
@bryanlundberg If you like my work I would like to work on other 2 sections as well.
Please create an issue on that.

2024-10-03 15:08 UTC, bryanlundberg requested changes
Hey @namansharma3007 UI looks very good 😅

Regarding the code, there are several minor refactoring opportunities, but nothing critical. My only concern is that if a user manually enters an invalid /settings sub-URL, the page stays blank. It would be better if the logic redirected any non-matching sub-URL back to /settings.

![image](https://github.com/user-attachments/assets/4ad4bba3-083a-4d7e-b08b-0b52e7dfff5c)

2024-10-03 15:24 UTC, namansharma3007 commented
> Hey @namansharma3007 UI looks very good 😅
> 
> Regarding the code, there are several minor refactoring opportunities, but nothing critical. My only concern is that if a user manually enters an invalid /settings sub-URL, the page stays blank. It would be better if the logic redirected any non-matching sub-URL back to /settings.
> 
> ![image](https://private-user-images.githubusercontent.com/119996547/373308501-4ad4bba3-083a-4d7e-b08b-0b52e7dfff5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Njg4NTMsIm5iZiI6MTcyNzk2ODU1MywicGF0aCI6Ii8xMTk5OTY1NDcvMzczMzA4NTAxLTRhZDRiYmEzLTA4M2EtNGQ3ZS1iMDhiLTBiNTJlN2RmZmY1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNTE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmFkYzliOWNhMWU1NjhkZDU5MmJlYThlYWI5NmY0MDBhMDM1OWU0ZWI5Y2Y4M2YxNzlmOGEzN2JjMjJmZDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3CkKawUpB7onXScGNu-0PnmwAifQc5_vLG9EbMXY_Sk)

Would you also like to implement the functionality that if user enters random text, the random text must disappear from URL, or it must stay there??

2024-10-03 15:47 UTC, bryanlundberg commented
> > Hey @namansharma3007 UI looks very good 😅
> > Regarding the code, there are several minor refactoring opportunities, but nothing critical. My only concern is that if a user manually enters an invalid /settings sub-URL, the page stays blank. It would be better if the logic redirected any non-matching sub-URL back to /settings.
> > ![image](https://private-user-images.githubusercontent.com/119996547/373308501-4ad4bba3-083a-4d7e-b08b-0b52e7dfff5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Njg4NTMsIm5iZiI6MTcyNzk2ODU1MywicGF0aCI6Ii8xMTk5OTY1NDcvMzczMzA4NTAxLTRhZDRiYmEzLTA4M2EtNGQ3ZS1iMDhiLTBiNTJlN2RmZmY1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNTE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmFkYzliOWNhMWU1NjhkZDU5MmJlYThlYWI5NmY0MDBhMDM1OWU0ZWI5Y2Y4M2YxNzlmOGEzN2JjMjJmZDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3CkKawUpB7onXScGNu-0PnmwAifQc5_vLG9EbMXY_Sk)
> 
> Would you also like to implement the functionality that if user enters random text, the random text must disappear from URL, or it must stay there?? User can also be redirected to page not found.

Redirect to /settings would be fine.

2024-10-03 17:39 UTC, namansharma3007 commented
> > > Hey @namansharma3007 UI looks very good 😅
> > > Regarding the code, there are several minor refactoring opportunities, but nothing critical. My only concern is that if a user manually enters an invalid /settings sub-URL, the page stays blank. It would be better if the logic redirected any non-matching sub-URL back to /settings.
> > > ![image](https://private-user-images.githubusercontent.com/119996547/373308501-4ad4bba3-083a-4d7e-b08b-0b52e7dfff5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Njg4NTMsIm5iZiI6MTcyNzk2ODU1MywicGF0aCI6Ii8xMTk5OTY1NDcvMzczMzA4NTAxLTRhZDRiYmEzLTA4M2EtNGQ3ZS1iMDhiLTBiNTJlN2RmZmY1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNTE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmFkYzliOWNhMWU1NjhkZDU5MmJlYThlYWI5NmY0MDBhMDM1OWU0ZWI5Y2Y4M2YxNzlmOGEzN2JjMjJmZDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3CkKawUpB7onXScGNu-0PnmwAifQc5_vLG9EbMXY_Sk)
> > 
> > 
> > Would you also like to implement the functionality that if user enters random text, the random text must disappear from URL, or it must stay there?? User can also be redirected to page not found.
> 
> Redirect to /settings would be fine.

I have resolved the isse: https://github.com/ProyectLink/super-list-frontend/pull/40

2024-10-04 19:29 UTC, bryanlundberg reviewed
I can't accept changes on package-lock.json and package.json files when it's not necessary,

2024-10-04 19:31 UTC, namansharma3007 commented on package.json
> +    "super-list-clone": "file:",
I cloned this repo twice. It comes when I run the project. But does not affect the functionality of code.

2024-10-04 19:33 UTC, namansharma3007 commented on package.json
> +    "super-list-clone": "file:",
I can commit new changes after removing this. Will that be ok?

2024-10-06 21:27 UTC, bryanlundberg commented on package.json
> +    "super-list-clone": "file:",
The issue I want to avoid, is for other people that will need to fix conflict on same code line modifications before PR.

2024-10-06 21:27 UTC, closed without merging

2024-10-06 21:28 UTC, bryanlundberg commented
foward to #40