popup upgrade pro dialog component is created
ProyectLink/super-list-frontend pull request #43
Opened 2024-10-05 15:16 UTC by adilkadivala

solved #24

When you click the upgrade to pro button, it should open the dialog.

2024-10-06 21:10 UTC, bryanlundberg requested changes
It's going to be hard to merge this PR.

I would recommend start again, because you over implemented the solution that was needed originally. Dialogs don't need a handler.

2024-10-06 21:10 UTC, bryanlundberg commented on src/components/navigation/Navigation.tsx
> +          </Button>
Here you should directly insert the dialog logic (sample on shadcn dialogs section)
And only create a new component for the dialog content.

2024-10-06 21:10 UTC, bryanlundberg commented on src/components/navigation/Pricing.tsx
Not even close

![image](https://github.com/user-attachments/assets/9222f52e-9e27-4ff5-94cf-46fe10c9a7a4)

![image](https://github.com/user-attachments/assets/88c051a2-6d10-43c6-a3a2-e24aade39974)

2024-10-06 21:10 UTC, bryanlundberg commented on src/components/ui/button.tsx
You should not commit files with only format changes.

2024-10-07 03:28 UTC, adilkadivala commented
Let me be close to issue,  

Here is what I understood..

when some one click on "upgrade to pro" button,  then pricing component should be poped up, and it should be close when click on "x" mark ,  and it will also closed when clicked outside of component.

![allTasks](https://github.com/user-attachments/assets/7d8211a9-87b1-491e-bc7c-81816d1c1f11)

please look at here mine local machine 


https://github.com/user-attachments/assets/72543912-a7fa-4847-a777-46f80003888e

so for opening on Click I have passed props hanlder

 <LayoutApplicationNavigation>
          <Navigation />
          <Navigation handleDialog={handleDialog} />
        </LayoutApplicationNavigation>
        
        
now I'm waiting to you response for more clearity.

2024-10-07 03:56 UTC, adilkadivala commented
oh sorry!! my bad.. 

I just realize that we didn't need to create any handler when we use shadcn ui,  sorry,  

let me solve it

2024-10-07 12:58 UTC, bryanlundberg commented
I suggest start a new branch @adilkadivala 👌

2024-10-07 12:58 UTC, closed without merging