Added inbox page and fixed hover effect in navigation items
ProyectLink/super-list-frontend pull request #44
Opened 2024-10-06 03:51 UTC by krishnkant-singh

2024-10-06 21:19 UTC, bryanlundberg requested changes
Hi @krishnkant-singh could you refactor the logic for detecting the navbar hover status. Also include the real navigation on click. Please 👋

2024-10-06 21:19 UTC, bryanlundberg commented on src/components/navigation/Navigation.tsx
> +  const [activeIndex, setActiveIndex] = useState(-1);
This is not going to work for a navbar. I suggest to verify the path.

2024-10-07 14:37 UTC, krishnkant-singh commented
hi @bryanlundberg i wanna know if active status represents hover thing or the page you are on

2024-10-07 15:09 UTC, bryanlundberg commented
> hi @bryanlundberg i wanna know if active status represents hover thing or the page you are on

It's both, represents the style for hover and current active.

2024-10-17 12:12 UTC, closed without merging